- menu_name: "Navigazione"

- name: "Home"
  url: "/"
  title: "Home"

- name: "Statuto"
  url: "/about"
  title: "Leggi lo statuto"

- name: "Eventi"
  url: "/eventi"
  title: 

- name: "Gruppo di studio"
  url: "/benkyokai/"
  title: 

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"
